---

- hosts: worker
  gather_facts: no
  become: yes

  tasks:
    - name: Get the token for joining the worker nodes
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command
      run_once: yes
      delegate_to: master

    - name: workers nodes
      when: "'worker' in group_names"
      block:
        - name: Leave cluster
          shell:
            cmd: kubeadm reset -f && iptables -F

        - name: Join cluster
          shell:
            cmd: "{{ kubernetes_join_command.stdout }}"

        - name: Add worker role
          tags: label
          become: no
          shell:
            cmd: kubectl label node {{ inventory_hostname }} node-role.kubernetes.io/worker=worker
          delegate_to: localhost