# docker run -p 80:80 kennethreitz/httpbin

# https://kubernetes.io/docs/tasks/debug/debug-application/debug-service/
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  selector:
    matchLabels:
      run: httpbin
  replicas: 1
  template:
    metadata:
      labels:
        run: httpbin
    spec:
      containers:
      - name: httpbin
        image: kennethreitz/httpbin
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    run: httpbin
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 30080
    protocol: TCP
    name: http
  externalTrafficPolicy: Cluster
  selector:
    run: httpbin

---
